CREATE OR REPLACE TRIGGER VICTIMIZACION_SEXO_EDAD_incr
BEFORE INSERT ON VICTIMIZACION_SEXO_EDAD 
FOR EACH ROW
BEGIN
  SELECT VICTIMIZACION_SEXO_EDAD_seq.NEXTVAL
  INTO   :new.id_victimizacion
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER VICTIMIZACION_VIOGEN_FAM_incr
BEFORE INSERT ON VICTIMIZACION_VIOGEN_FAM
FOR EACH ROW
BEGIN
  SELECT VICTIMIZACION_VIOGEN_FAM_seq.NEXTVAL
  INTO   :new.id_victimizacion
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER VICTIMIZACION_ODIO_incr
BEFORE INSERT ON VICTIMIZACION_ODIO 
FOR EACH ROW
BEGIN
  SELECT VICTIMIZACION_ODIO_seq.NEXTVAL
  INTO   :new.id_victimizacion
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER VICTIMIZACION_SERIE_incr
BEFORE INSERT ON VICTIMIZACION_SERIE
FOR EACH ROW
BEGIN
  SELECT VICTIMIZACION_SERIE_seq.NEXTVAL
  INTO   :new.id_victimizacion
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER DELITO_TIPO_incr
BEFORE INSERT ON DELITO_TIPO
FOR EACH ROW
BEGIN
  SELECT DELITO_TIPO_seq.NEXTVAL
  INTO   :new.id_delito
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER DELITO_PROV_incr
BEFORE INSERT ON DELITO_PROVINCIA
FOR EACH ROW
BEGIN
  SELECT DELITO_PROV_seq.NEXTVAL
  INTO   :new.id_delito
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER DELITO_EXTR_TIPO_incr
BEFORE INSERT ON DELITO_EXTR_TIPO
FOR EACH ROW
BEGIN
  SELECT DELITO_EXTR_TIPO_seq.NEXTVAL
  INTO   :new.id_delito
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER DELITO_EXTR_PROV_incr
BEFORE INSERT ON DELITO_EXTR_PROVINCIA
FOR EACH ROW
BEGIN
  SELECT DELITO_EXTR_PROV_seq.NEXTVAL
  INTO   :new.id_delito
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER DELITO_EXTR_NACIONALIDAD_incr
BEFORE INSERT ON DELITO_EXTR_NACIONALIDAD
FOR EACH ROW
BEGIN
  SELECT DELITO_EXTR_NACIONALIDAD_seq.NEXTVAL
  INTO   :new.id_delito
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER DELITO_EXTR_SERIE_incr
BEFORE INSERT ON DELITO_EXTR_SERIE
FOR EACH ROW
BEGIN
  SELECT DELITO_EXTR_SERIE_seq.NEXTVAL
  INTO   :new.id_delito
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER DELITO_MENORES_incr
BEFORE INSERT ON DELITO_MENORES
FOR EACH ROW
BEGIN
  SELECT DELITO_MENORES_seq.NEXTVAL
  INTO   :new.id_delito
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER DELITO_EDAD_SEXO_TIPO_incr
BEFORE INSERT ON DELITO_EDAD_SEXO_TIPO
FOR EACH ROW
BEGIN
  SELECT DELITO_EDAD_SEXO_TIPO_seq.NEXTVAL
  INTO   :new.id_delito
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER DELITO_EDAD_SEXO_PROV_incr
BEFORE INSERT ON DELITO_EDAD_SEXO_PROVINCIA
FOR EACH ROW
BEGIN
  SELECT DELITO_EDAD_SEXO_PROV_seq.NEXTVAL
  INTO   :new.id_delito
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER DELITO_EDAD_SERIE_incr
BEFORE INSERT ON DELITO_EDAD_SERIE
FOR EACH ROW
BEGIN
  SELECT DELITO_EDAD_SERIE_seq.NEXTVAL
  INTO   :new.id_delito
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER REGISTRO_PROVINCIA_incr
BEFORE INSERT ON REGISTRO_PROVINCIA
FOR EACH ROW
BEGIN
  SELECT REGISTRO_PROVINCIA_seq.NEXTVAL
  INTO   :new.id_registro_prov
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER REGISTRO_COMUNIDAD_incr
BEFORE INSERT ON REGISTRO_COMUNIDAD
FOR EACH ROW
BEGIN
  SELECT REGISTRO_COMUNIDAD_seq.NEXTVAL
  INTO   :new.id_registro_ccaa
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER PAIS_incr
BEFORE INSERT ON PAIS
FOR EACH ROW
BEGIN
  SELECT PAIS_seq.NEXTVAL
  INTO   :new.id_pais
  FROM   dual;
END;
/